export const FETCH_QUESTIONS_START = 'FETCH_QUESTIONS_START';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAIL = 'FETCH_QUESTIONS_FAIL';

export const ADD_USER_ANSWER = 'ADD_USER_ANSWER';

export const QUIZ_TIME_START = 'QUIZ_TIME_START';
export const QUIZ_TIME_END = 'QUIZ_TIME_END';

export const GET_RESULT = 'GET_RESULT';
